openapi: 3.0.0
info:
  title: amokjs
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /json:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                /json:
                  value:
                    array:
                      - 1
                      - 2
                      - 3
                    boolean: true
                    'null': null
                    number: 123
                    object:
                      a: b
                      c: d
                      e: f
                    string: Hello World
      operationId: get-json
      description: /resource/hosted/js/jsonを返す。
  /about:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                /about:
                  value:
                    amock: quick way to build mocks in Apigee Edge
                    about: this projects is powered by Node.js and native Apigee Edge XML policies
                    author: '@test'
      operationId: get-about
      description: /resource/hosted/js/aboutを返す。
components:
  schemas: {}
